project:
  type: website
  
resources:
  - data/interactive_wordcloud.html
  - data/tags/**
  - data/wordcloud2/wordcloud.html
  - data/wordcloud2/word_data.js

website:
  title: "Chris Oldmeadow"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about/about.qmd
      - text: "Experience"
        href: about/experience.qmd
      - text: "Publications"
        href: publications.qmd
      - text: "Grants"
        href: grants.qmd
      - text: "Projects & Presentations"
        href: projects_presentations.qmd
      - text: "CV"
        href: cv/CV-Oldmeadow.pdf

format:
  html:
    theme: yeti
    css: styles.css
    includes:
      in-header: fontawesome.html
